name: 'milvus_environment'
services:
  milvus_db:
    image: milvusdb/milvus:v2.4.0-rc.1
    security_opt:
      - "seccomp:unconfined"
    environment:
      - ETCD_USE_EMBED=true
      - ETCD_DATA_DIR=/var/lib/milvus/etcd
      - ETCD_CONFIG_PATH=/milvus/configs/embedEtcd.yaml
      - COMMON_STORAGETYPE=local
    volumes:
      - ./milvus_db/volumes/milvus:/var/lib/milvus
      - ./milvus_db:/milvus/configs/embedEtcd.yaml
    ports:
      - "19530:19530"
      - "9091:9091"
      - "2379:2379"
    healthcheck:
      test: "curl -f http://localhost:9091/healthz"
      interval: "30s"
      start_period: "90s"
      timeout: "20s"
      retries: 3
    command: 'milvus run standalone  1> /dev/null'
  milvus_admin:
    image: zilliz/attu:v2.3.10
    ports:
      - "8000:3000"
    environment:
      - MILVUS_URL="milvus_db:19530"